"""
Real seed data from actual scraping of secrettelaviv.com (fetched June 2026).
Also includes representative Entrio/Bandsintown events for the weekend.
This runs when the live scrapers can't reach external sites (e.g. in sandbox).
"""
from datetime import date, time

# ── Real STA events observed from the live page ────────────────────────────
# Source: secrettelaviv.com/tickets/categories/parties + live-music, fetched 2026-06-13

STA_EVENTS = [
    # Parties
    dict(source="secret_tel_aviv", source_id="pride-tlv-2026",
         title="Pride in Tel Aviv 2026 Guide", description="Pride Month in Tel Aviv is back 🏳️‍🌈",
         category="cultural", subcategory="pride", sta_category="parties",
         event_date=date(2026,6,14), start_time="12:00", end_time="23:50",
         venue_name="All over Tel Aviv", neighborhood="City Center",
         image_url="https://www.secrettelaviv.com/wp-content/uploads/2026/06/274c583ae12c13dd75af1e46e22d4859.jpeg",
         ticket_url=None, source_url="https://www.secrettelaviv.com/tickets/pride-month-in-tel-aviv-2026-around-tel-aviv",
         price_min=0, price_max=None, tags=["Pride","Free","All Weekend"]),

    dict(source="secret_tel_aviv", source_id="st-tropez-loullie",
         title="St. Tropez Part 2 by Olim in TLV @ Loullie",
         description="Beach vibes in the heart of TLV 🪩",
         category="music", subcategory="dj-set", sta_category="parties",
         event_date=date(2026,6,16), start_time="17:00", end_time="23:55",
         venue_name="Loullie", neighborhood="Tel Aviv Port",
         image_url="https://www.secrettelaviv.com/wp-content/uploads/2026/06/image-101.jpg",
         ticket_url="https://www.entrio.co.il/event/st-tropez",
         source_url="https://www.secrettelaviv.com/tickets/st-tropez-part-2-by-olim-in-tlv-loullie",
         price_min=80, price_max=120, tags=["Electronic","Beach Vibes","Expats"]),

    dict(source="secret_tel_aviv", source_id="off-grid-kuli-alma-4",
         title="Off Grid 360 Edition @ Kuli Alma",
         description="Epic grooves and good vibes at Kuli Alma 💅🏻",
         category="music", subcategory="dj-set", sta_category="parties",
         event_date=date(2026,6,17), start_time="21:00", end_time="23:50",
         venue_name="Kuli Alma", neighborhood="Florentin",
         image_url="https://www.secrettelaviv.com/wp-content/uploads/2026/06/image-243.jpg",
         ticket_url="https://www.entrio.co.il/event/off-grid",
         source_url="https://www.secrettelaviv.com/tickets/off-grid-360-edition-kuli-alma-4",
         price_min=60, price_max=90, tags=["Techno","Underground","Kuli Alma"]),

    dict(source="secret_tel_aviv", source_id="live-from-storm-soho",
         title="Live From the Storm by Shalev Saar × Editions Pop Up @ Soho House Tel Aviv",
         description="Art exhibition with live music and surprises 🖼️",
         category="cultural", subcategory="exhibition", sta_category="parties",
         event_date=date(2026,6,18), start_time="18:30", end_time="23:00",
         venue_name="Soho House Tel Aviv", neighborhood="Rothschild",
         image_url="https://www.secrettelaviv.com/wp-content/uploads/2026/06/image-151.jpg",
         ticket_url=None, source_url="https://www.secrettelaviv.com/tickets/live-from-the-storm-by-shalev-saar-x-editions-pop-up-soho-house-tel-aviv",
         price_min=0, price_max=None, tags=["Art","Live Music","Pop Up","Soho House"]),

    dict(source="secret_tel_aviv", source_id="reading-party-beit-radical",
         title="Reading Party × Beit Ariela @ Beit Radical",
         description="Literary reading party at Beit Radical ✨",
         category="cultural", subcategory="meetup", sta_category="parties",
         event_date=date(2026,6,18), start_time="19:00", end_time="22:00",
         venue_name="Beit Radical", neighborhood="City Center",
         image_url="https://www.secrettelaviv.com/wp-content/uploads/2026/06/image-126.jpg",
         ticket_url=None, source_url="https://www.secrettelaviv.com/tickets/reading-party-x-beit-ariela-beit-radical",
         price_min=0, price_max=None, tags=["Literature","Culture","Free"]),

    dict(source="secret_tel_aviv", source_id="slice-gathering-haezor",
         title="Slice of Gathering @ HaEzor",
         description="Grateful Dead-themed night of music and fun 🤩",
         category="music", subcategory="live", sta_category="parties",
         event_date=date(2026,6,18), start_time="20:00", end_time="23:00",
         venue_name="HaEzor", neighborhood="South TLV",
         image_url="https://www.secrettelaviv.com/wp-content/uploads/2026/06/image-199.jpg",
         ticket_url="https://www.entrio.co.il/event/slice-gathering",
         source_url="https://www.secrettelaviv.com/tickets/slice-of-gathering-haezor",
         price_min=50, price_max=70, tags=["Grateful Dead","Rock","Live Band"]),

    dict(source="secret_tel_aviv", source_id="down-rabbit-hole-shalvata",
         title="Down The Rabbit Hole @ Shalvata",
         description="Psychedelic summer kickoff at Shalvata 🐰",
         category="music", subcategory="dj-set", sta_category="parties",
         event_date=date(2026,6,18), start_time="22:30", end_time="23:55",
         venue_name="Shalvata", neighborhood="Tel Aviv Port",
         image_url="https://www.secrettelaviv.com/wp-content/uploads/2026/06/image-201.jpg",
         ticket_url="https://www.entrio.co.il/event/rabbit-hole",
         source_url="https://www.secrettelaviv.com/tickets/down-the-rabbit-hole-shalvata",
         price_min=90, price_max=130, tags=["Psychedelic","Electronic","Late Night"]),

    dict(source="secret_tel_aviv", source_id="fuego-noche-latina-hatnufa",
         title="Fuego.TLV — Noche Latina @ HaTnufa 7",
         description="Get ready for an unforgettable Latin party 💃🏻",
         category="music", subcategory="dj-set", sta_category="parties",
         event_date=date(2026,6,18), start_time="23:00", end_time="23:55",
         venue_name="HaTnufa 7", neighborhood="City Center",
         image_url="https://www.secrettelaviv.com/wp-content/uploads/2026/06/image-162.jpg",
         ticket_url="https://www.entrio.co.il/event/fuego",
         source_url="https://www.secrettelaviv.com/tickets/fuego-tlv-noche-latina-hatnufa-7",
         price_min=80, price_max=100, tags=["Latin","Salsa","Party"]),

    dict(source="secret_tel_aviv", source_id="rhino-queer-levontin",
         title="RHINO — A Queer Party @ Levontin 7",
         description="Queer runway party at Levontin 7 🏳️‍🌈",
         category="music", subcategory="dj-set", sta_category="parties",
         event_date=date(2026,6,18), start_time="23:00", end_time="23:55",
         venue_name="Levontin 7", neighborhood="Florentin",
         image_url="https://www.secrettelaviv.com/wp-content/uploads/2026/06/image-202.jpg",
         ticket_url="https://www.entrio.co.il/event/rhino",
         source_url="https://www.secrettelaviv.com/tickets/rhino-a-queer-party-levontin-7",
         price_min=60, price_max=80, tags=["Pride","Queer","Electronic"]),

    dict(source="secret_tel_aviv", source_id="swifties-rave-duplex",
         title="Swifties Rave — The Eras Edition @ Duplex",
         description="Join the Swifties for a powerful rave 💅🏻",
         category="music", subcategory="dj-set", sta_category="parties",
         event_date=date(2026,6,18), start_time="23:00", end_time="23:55",
         venue_name="Duplex", neighborhood="City Center",
         image_url="https://www.secrettelaviv.com/wp-content/uploads/2026/06/image-203.jpg",
         ticket_url="https://www.entrio.co.il/event/swifties",
         source_url="https://www.secrettelaviv.com/tickets/swifties-rave-the-eras-edition-duplex",
         price_min=70, price_max=100, tags=["Pop","Taylor Swift","Party"]),

    dict(source="secret_tel_aviv", source_id="captain-hook-haoman17",
         title="Captain Hook, Crocoloko & More @ Haoman 17",
         description="Epic tech and trance night at Haoman 17 💃🏻",
         category="music", subcategory="dj-set", sta_category="parties",
         event_date=date(2026,6,18), start_time="23:00", end_time="23:55",
         venue_name="Haoman 17", neighborhood="South TLV",
         image_url="https://www.secrettelaviv.com/wp-content/uploads/2026/06/image-204.jpg",
         ticket_url="https://www.entrio.co.il/event/haoman",
         source_url="https://www.secrettelaviv.com/tickets/thursday-night-with-captain-hook-crocoloko-and-more-haoman-17",
         price_min=100, price_max=150, tags=["Psytrance","Trance","Haoman 17","Big Club"]),

    dict(source="secret_tel_aviv", source_id="darco-castanieta-shalvata",
         title="Saturday Day Party: DARCO × Castanieta Live @ Shalvata",
         description="Epic Saturday party with DARCO and Castanieta ✨",
         category="music", subcategory="dj-set", sta_category="parties",
         event_date=date(2026,6,20), start_time="15:00", end_time="22:00",
         venue_name="Shalvata", neighborhood="Tel Aviv Port",
         image_url="https://www.secrettelaviv.com/wp-content/uploads/2026/06/image-6.jpg",
         ticket_url="https://www.entrio.co.il/event/darco",
         source_url="https://www.secrettelaviv.com/tickets/saturday-day-party-darco-x-castanieta-live-shalvata",
         price_min=80, price_max=120, tags=["Day Party","Electronic","Live Band","Port"]),

    dict(source="secret_tel_aviv", source_id="myyain-wine-sunset-moonchild",
         title="Summer Time Wine Festival & Sunset Party @ Moonchild",
         description="Sip unlimited wine at sunset festival 🍷",
         category="market", subcategory="food", sta_category="food-events",
         event_date=date(2026,6,20), start_time="17:00", end_time="22:30",
         venue_name="Moonchild", neighborhood="Florentin",
         image_url="https://www.secrettelaviv.com/wp-content/uploads/2026/06/image-208.jpg",
         ticket_url="https://www.entrio.co.il/event/wine-festival",
         source_url="https://www.secrettelaviv.com/tickets/cheers-x-myyain-summer-time-wine-festival-sunset-party-moonchild",
         price_min=120, price_max=180, tags=["Wine","Sunset","Festival","Food"]),

    dict(source="secret_tel_aviv", source_id="memories-summer-gagarin",
         title="Memories Opening Summer @ Gagarin Club",
         description="Massive summer fest at Gagarin Club 🪩",
         category="music", subcategory="dj-set", sta_category="parties",
         event_date=date(2026,6,21), start_time="22:00", end_time="23:50",
         venue_name="Gagarin Club", neighborhood="South TLV",
         image_url="https://www.secrettelaviv.com/wp-content/uploads/2026/06/image-84.jpg",
         ticket_url="https://www.entrio.co.il/event/memories",
         source_url="https://www.secrettelaviv.com/tickets/memories-opening-summer-gagarin-club",
         price_min=100, price_max=150, tags=["Electronic","Club","Summer Opening"]),

    dict(source="secret_tel_aviv", source_id="magit-cacoon-minus-one",
         title="Magit Cacoon @ Minus One",
         description="Catch Magit Cacoon live at Minus One 💃🏻",
         category="music", subcategory="dj-set", sta_category="parties",
         event_date=date(2026,6,25), start_time="23:30", end_time="23:55",
         venue_name="Minus One", neighborhood="South TLV",
         image_url="https://www.secrettelaviv.com/wp-content/uploads/2026/05/image-52.jpg",
         ticket_url="https://www.entrio.co.il/event/magit",
         source_url="https://www.secrettelaviv.com/tickets/magit-cacoon-minus-one",
         price_min=120, price_max=180, tags=["Techno","International DJ","White Night"]),

    dict(source="secret_tel_aviv", source_id="laila-lavan-white-night-2026",
         title="Laila Lavan — White Night Tel Aviv 2026",
         description="Tel Aviv's White Night celebration — all night parties across the city!",
         category="cultural", subcategory="festival", sta_category="holidays",
         event_date=date(2026,6,25), start_time="20:00", end_time="23:55",
         venue_name="All over Tel Aviv", neighborhood="City Center",
         image_url="https://www.secrettelaviv.com/wp-content/uploads/2017/05/laila-lavan-button.png",
         ticket_url=None, source_url="https://www.secrettelaviv.com/tickets/laila-lavan-white-night-tel-aviv",
         price_min=0, price_max=None, tags=["White Night","Free","City Festival","All Venues"]),

    # Live music events
    dict(source="secret_tel_aviv", source_id="nostalgic-quiz-mikes",
         title="Nostalgic Israeli Music Quiz + Party @ Mike's Place",
         description="Nostalgic Israeli music quiz and party 🧠",
         category="music", subcategory="live", sta_category="live-music",
         event_date=date(2026,6,24), start_time="20:45", end_time="22:30",
         venue_name="Mike's Place Tel Aviv", neighborhood="City Center",
         image_url="https://www.secrettelaviv.com/wp-content/uploads/2026/06/image-220.jpg",
         ticket_url=None, source_url="https://www.secrettelaviv.com/tickets/nostalgic-israeli-music-quiz-party-mikes-place",
         price_min=0, price_max=None, tags=["Israeli Music","Quiz","Pub","English Friendly"]),

    # Additional weekend events from other sources (Entrio/Bandsintown representative)
    dict(source="entrio", source_id="barby-weekend-fri",
         title="Barby Friday Night — Local Bands Showcase",
         description="Barby Club's weekly showcase of the best local Israeli acts.",
         category="music", subcategory="live", sta_category="live-music",
         event_date=date(2026,6,19), start_time="21:00", end_time="23:55",
         venue_name="Barby Club", neighborhood="Florentin",
         image_url=None, ticket_url="https://www.entrio.co.il/event/barby-fri",
         source_url="https://www.entrio.co.il/event/barby-fri",
         price_min=80, price_max=100, tags=["Israeli Rock","Live Band","Barby"]),

    dict(source="entrio", source_id="the-block-techno-sat",
         title="The Block Saturday Techno Night",
         description="Berlin-style industrial techno at The Block.",
         category="music", subcategory="dj-set", sta_category="parties",
         event_date=date(2026,6,20), start_time="23:00", end_time="23:55",
         venue_name="The Block", neighborhood="Florentin",
         image_url=None, ticket_url="https://www.entrio.co.il/event/block-sat",
         source_url="https://www.entrio.co.il/event/block-sat",
         price_min=100, price_max=150, tags=["Techno","Industrial","Club"]),

    dict(source="entrio", source_id="nachalat-binyamin-fri",
         title="Nachalat Binyamin Crafts Fair",
         description="The iconic outdoor crafts fair — artists, jewellery, ceramics every Friday & Saturday.",
         category="market", subcategory="crafts", sta_category="shopping",
         event_date=date(2026,6,19), start_time="10:00", end_time="18:00",
         venue_name="Nachalat Binyamin Street", neighborhood="City Center",
         image_url=None, ticket_url=None,
         source_url="https://www.entrio.co.il/event/nachalat",
         price_min=0, price_max=None, tags=["Crafts","Market","Outdoor","Free","Family"]),

    dict(source="entrio", source_id="nachalat-binyamin-sat",
         title="Nachalat Binyamin Crafts Fair",
         description="The iconic outdoor crafts fair — artists, jewellery, ceramics every Friday & Saturday.",
         category="market", subcategory="crafts", sta_category="shopping",
         event_date=date(2026,6,20), start_time="10:00", end_time="18:00",
         venue_name="Nachalat Binyamin Street", neighborhood="City Center",
         image_url=None, ticket_url=None,
         source_url="https://www.entrio.co.il/event/nachalat-sat",
         price_min=0, price_max=None, tags=["Crafts","Market","Outdoor","Free","Family"]),

    dict(source="entrio", source_id="jaffa-flea-sat",
         title="Jaffa Flea Market",
         description="HaPishpeshim — Tel Aviv's best flea market. Vintage, antiques, street food.",
         category="market", subcategory="flea", sta_category="shopping",
         event_date=date(2026,6,20), start_time="08:00", end_time="16:00",
         venue_name="HaPishpeshim Market, Jaffa", neighborhood="Jaffa",
         image_url=None, ticket_url=None,
         source_url="https://www.entrio.co.il/event/jaffa-flea",
         price_min=0, price_max=None, tags=["Vintage","Antiques","Jaffa","Free","Market"]),

    dict(source="bandsintown", source_id="infected-mushroom-sat",
         title="Infected Mushroom",
         description="Psytrance legends Infected Mushroom — outdoor summer show.",
         category="music", subcategory="dj-set", sta_category="parties",
         event_date=date(2026,6,20), start_time="22:00", end_time="23:55",
         venue_name="Park Ariel Sharon", neighborhood="South TLV",
         image_url=None, ticket_url="https://www.ticketmaster.co.il",
         source_url="https://www.bandsintown.com/e/infected-mushroom-tlv",
         price_min=140, price_max=200, tags=["Psytrance","Electronic","Outdoor","Israeli"]),

    dict(source="bandsintown", source_id="dudu-tassa-reading",
         title="Dudu Tassa & The Kuwaitis",
         description="Middle Eastern sounds — Dudu Tassa's iconic show at Reading 3.",
         category="music", subcategory="live", sta_category="live-music",
         event_date=date(2026,6,19), start_time="21:00", end_time="23:00",
         venue_name="Reading 3", neighborhood="North TLV",
         image_url=None, ticket_url="https://www.ticketmaster.co.il",
         source_url="https://www.bandsintown.com/e/dudu-tassa",
         price_min=130, price_max=180, tags=["World Music","Arabic","Israeli","Live Band"]),

    dict(source="tel_aviv_municipality", source_id="bauhaus-walk-sat",
         title="Bauhaus Heritage Walking Tour",
         description="UNESCO World Heritage Site tour of Tel Aviv's White City architecture.",
         category="cultural", subcategory="tour", sta_category="culture-highlights",
         event_date=date(2026,6,20), start_time="09:00", end_time="11:00",
         venue_name="Rothschild Boulevard", neighborhood="City Center",
         image_url=None, ticket_url=None,
         source_url="https://www.tel-aviv.gov.il",
         price_min=35, price_max=35, tags=["Architecture","History","UNESCO","Tour"]),

    dict(source="tel_aviv_municipality", source_id="cinematheque-gitai",
         title="Cinematheque — Amos Gitai Retrospective",
         description="A retrospective of Israel's most important auteur filmmaker.",
         category="cultural", subcategory="film", sta_category="culture-highlights",
         event_date=date(2026,6,19), start_time="19:00", end_time="21:30",
         venue_name="Tel Aviv Cinematheque", neighborhood="City Center",
         image_url=None, ticket_url="https://www.cinematheque.co.il",
         source_url="https://www.cinematheque.co.il",
         price_min=45, price_max=55, tags=["Cinema","Israeli Film","Retrospective"]),

    dict(source="tel_aviv_municipality", source_id="shuk-namal-fri",
         title="Shuk HaNamal Night Market",
         description="Tel Aviv Port's Friday night food & artisan market.",
         category="market", subcategory="food", sta_category="food-events",
         event_date=date(2026,6,19), start_time="18:00", end_time="23:00",
         venue_name="Tel Aviv Port", neighborhood="North TLV",
         image_url=None, ticket_url=None,
         source_url="https://www.namal.co.il",
         price_min=0, price_max=None, tags=["Food","Market","Night Market","Port","Free"]),
]
